### ISSUE TITLE
Syndication to Twitter doesn't work

### ISSUE THREAD

**Issue by alienlebarge** [alienlebarge/alb-indiekit#6]
### Description

I configured @indiekit/syndicator-plugin #4
When I post notes, they are note syndicated on Twitter

### Ask

Fix the problem

### To Do

- [x] Regenerates keys &tokens
- [x] Set app permissions to _Read, Write, and Direct Messages_
- [x] Connect IndieKit to MangoDV using the user defined in _DataBase Access_

### Additional Info

- https://github.com/getindiekit/indiekit/tree/main/packages/syndicator-twitter
- https://alienlebarge.ch/notes/20210125131839/
- https://alienlebarge.ch/notes/20210125164447/
- https://alienlebarge.ch/notes/20210125202616/

**Comment by alienlebarge** [comment]
@paulrobertlloyd perhaps, you can help me.

I have config the plugin but the cross-posting do not work.
Is there something special to change in heroku or twitter app config ?

**Comment by paulrobertlloyd** [comment]
I’d hold on for a bit; I broke something in a recent change, and haven’t got round to figuring out what. Everything was working for about 2 minutes, then things started falling apart again 😅

**Comment by alienlebarge** [comment]
I forgot to set `publication.syndicationTargets`. I fix it but syndication to Twitter still not work 
- c2b3431252e923b9ddef6da7a3880f25c5ac3161
- 4f7a96820abd87dc4a2d10b04544f2ce1f6165f1

**Comment by paulrobertlloyd** [comment]
There’s a new alpha release of Indiekit; give that a go and let me know if the problems still persists. 😀

**Comment by alienlebarge** [comment]
@paulrobertlloyd thanks for the message 👍

I have upgraded indiekit to the latest version version and posted a note but it doesn't show up on twitter.
- alienlebarge/alienlebargech-v3@a7cc5ec5747619864bba36ffdd41e129e8ea3359
- https://alienlebarge.ch/notes/20210201090826/
- https://twitter.com/alienlebarge

Do not now where the error comes from ... 😓

**Comment by paulrobertlloyd** [comment]
Have you pinged the syndication endpoint? https://indiekit.alienlebarge.ch/syndicate?token=[accessToken]

You can find your access token on the status page.

**Comment by alienlebarge** [comment]
Not sure I can ping a subfolder ... !?

I can ping the root url
```shell
$ ping indiekit.alienlebarge.ch
PING descriptive-mistletoe-4dor86vmrdtstdzehoy97yuv.herokudns.com (3.248.160.195): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
^C
--- descriptive-mistletoe-4dor86vmrdtstdzehoy97yuv.herokudns.com ping statistics ---
7 packets transmitted, 0 packets received, 100.0% packet loss
```

but not the syndication endpoint
```shell
$ ping indiekit.alienlebarge.ch/syndicate?token=bliblablo
ping: cannot resolve indiekit.alienlebarge.ch/syndicate?token=bliblablo: Unknown host
```

**Comment by paulrobertlloyd** [comment]
Sorry, using slang where I should be more specific. You should send a `POST` request to that URL. With Netlify you can set a URL to post to after specific events happen (i.e. once a deploy has completed), but you could also do this with a cron job.

Out of interest, how is your site set up? How do you publish to the web? Where do you host your site?

**Comment by alienlebarge** [comment]
### `POST` request

Tried to send a `POST` request from my computer but I get a `404`.
![CleanShot 2021-02-02 at 06 40 57](https://user-images.githubusercontent.com/611234/106558317-d5ca5580-6523-11eb-81e7-0406282a9a41.png)

I tried to request heroku's app url `https://alb-indiekit.herokuapp.com/syndicate` too
![CleanShot 2021-02-02 at 08 36 50](https://user-images.githubusercontent.com/611234/106567341-f8636b00-6531-11eb-8e5b-1c9a9ce9f99d.png)


I have set a hook to send a `POST` request to `https://indiekit.alienlebarge.ch/syndicate?token=token` in Netlify but I do not know how to verify if it work.
![CleanShot 2021-02-02 at 07 00 29](https://user-images.githubusercontent.com/611234/106558689-6f920280-6524-11eb-98fe-6ba9d45ce92f.png)

### Site architecture
The repo of my site is [alienlebarge/alienlebargech-v3](https://github.com/alienlebarge/alienlebargech-v3). 

Here are the things that trigger a build in Netlify:
- Each commit to the `master`
- A Github action that trigger the build 3 times a day
- A Web hook from Webmention.io trigger a build on each new mention via Build hook in Netlify

DNS are managed by [www.infomaniak.com](https://www.infomaniak.com/)

**Comment by paulrobertlloyd** [comment]
So, a couple of things:

1. Wow, Paw looks like a great app. I’ve been using Postman, but might give this native app a go!
2. Looks like I need to localise the 404 error
3. Syndication requires setting up IndieKit to use a MongoDB database; the only way it can syndicate posts if it’s already got a version of it stored somewhere.

    I use [MongoDB Atlas](https://www.mongodb.com/cloud/atlas), which is free, but a but of a pain to understand. But once set up, you’ll have a URL something like: `mongodb+srv://USERNAME:PASSWORD@cluster0.ecvhr.mongodb.net/DATABASE?retryWrites=true&w=majority`.

    Set that as an environment variable (say `MONGODB_URL`), and then update your config: `indiekit.set('application.mongodbUrl', process.env.MONGODB_URL)`
4. I really need to improve the documentation around this.

**Comment by alienlebarge** [comment]
Thanks for the feedback.

I haven't understand that MongoDB is required.
I have tried to set it up but it not easy to understand. I haven't figured out what is the _database_. I have set up a _cluster_ but I do not know what is a the _database_.
This for sure not the better UX I have seen 😉

I will try again later...

**Comment by paulrobertlloyd** [comment]
So… I think without setting `application.mongodbUrl` this won’t work. Syndication depends on Indiekit being connected to a database. I think the experience could be improved here, so that this requirement is clearer.

This is what Im doing in my config file: https://github.com/paulrobertlloyd/paulrobertlloyd-indiekit/blob/f4171af68577c2129011d8fd56117cddc44930d4/index.js#L106-L107

**Comment by paulrobertlloyd** [comment]
Your MondoDB URL should look something like this `mongodb+srv://<USERNAME>:<PASSWORD>@cluster0.ecvhr.mongodb.net/<PROJECT>?retryWrites=true&w=majority

You can find it by clicking ‘CONNECT’:

<img width="335" alt="Screenshot 2021-07-08 at 23 06 28" src="https://user-images.githubusercontent.com/813383/124996628-30229180-e041-11eb-9bbc-d39f93b74e89.png">

Then choose ‘Connect your application’ and copy the URL shown.

**Comment by alienlebarge** [comment]
Here's what I have done:

I put the config back (7e95e2ed8944c776da0152895dd99880837cad99)

Then, I tried to locate the MongoDB url. So I clicked on the _CONNECT_ button and get the following modal:
![CleanShot 2021-07-09 at 19 51 28@2x](https://user-images.githubusercontent.com/611234/125118171-9cf46500-e0ef-11eb-8d11-74cf678e77b9.png)
Apparently, the url I have to use is `mongodb+srv://indiekit:<password>@alb-indiekit.2croy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`. But what is the `<password>` I have to use ? I tried with the indiekit token but appraently it's not that.

An other problem is that if the password or username to connect MongoDB are not right, indiekit crash.

**Comment by paulrobertlloyd** [comment]
> But what is the <password> I have to use ? I tried with the indiekit token but appraently it's not that.

This will be your MongoDB password, aka the one you use sign into Atlas with.

> An other problem is that if the password or username to connect MongoDB are not right, indiekit crash.

Yep, lots to do on improving the UX around the database requirement ☺️

**Comment by alienlebarge** [comment]
Thanks for the ultra kick answer.
I managed to make it works !

In fact, the `<password>` was the one from the `indiekit` user I have define in the _Database Access_ tab.
![CleanShot 2021-07-09 at 21 43 45](https://user-images.githubusercontent.com/611234/125128775-c9fc4400-e0fe-11eb-961f-b23be14f77d1.png)

---
Sidenote

I think Italy will win

**Comment by paulrobertlloyd** [comment]
Going to see if I can improve the documentation and UX around this soon.

> I think Italy will win

Sadly perceptive. 😢
